apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kevinstudy0829/docker-fastapi:7f3578447cf523fcda15f171774334b5e0bad0a3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000