apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kevinstudy0829/docker-fastapi:65b7fc31393ed601a04e8e887b30f1cc6a0198a4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000