apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kevinstudy0829/docker-fastapi:f399baad15294fcee916ca808cec07c10b382a5e
          imagePullPolicy: Always
          ports:
            - containerPort: 8000